on:  #events (push and pull_request)
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  flutter_version: '3.19.1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
#          version: latest
      - name: Check java version
        run: java --version
      - name: Check flutter version
        run: flutter --version